###Test action
POST http://localhost:4004/main/updateApprovalStatus
Content-Type: application/json

{
    "orderID" : "74fc1918-eaae-42fe-8e74-5406b5c53752",
    "decision": "Approve"
}


###Create order
POST http://localhost:4004/main/purchaseOrder
Content-Type: application/json

{
    "supplier" : "TEST",
    "requestedDeliveryDate" : "2023-03-31",
    "currency_code" : "USD",
    "amount" : 100.00
}